
/**
 * Automatically generated file containing the multiplier and shift factors
 * needed for the quadratic stack blur weight factors, for each radius. If you
 * go beyond the allowed radius, you're on your own.
 *
 * This file is generated by the TypeScript file `./src/js/generate-tables.ts`,
 * but you probably don't need to worry about it, because we typically commit
 * the generated code.
 */

const int quadratic_weight_maximum_radius = 63;
const int quadratic_weight_multipliers[] = { 0, 0, 171, 205, 171, 469, 137, 405, 137, 213, 313, 505, 391, 81, 261, 441, 365, 157, 265, 463, 199, 351, 153, 273, 481, 27, 385, 87, 313, 285, 129, 471, 429, 395, 361, 167, 307, 285, 263, 245, 227, 425, 395, 185, 173, 325, 19, 287, 269, 127, 239, 453, 427, 405, 383, 91, 345, 41, 39, 297, 141, 269, 257, 245 };
const unsigned int quadratic_weight_multipliers[] = { 0, 0, 11, 12, 13, 15, 14, 16, 15, 16, 17, 18, 18, 16, 18, 19, 19, 18, 19, 20, 19, 20, 19, 20, 21, 17, 21, 19, 21, 21, 20, 22, 22, 22, 22, 21, 22, 22, 22, 22, 22, 23, 23, 22, 22, 23, 19, 23, 23, 22, 23, 24, 24, 24, 24, 22, 24, 21, 21, 24, 23, 24, 24, 24 };
