/**
 * Generates the shift and multiplier tables for the C code, using TypeScript.
 * The code should be stable, so we can leave the files unchanged if the 
 * contents are identical.
 */

import { createHash } from 'node:crypto';
import fs from 'node:fs';

import { makeTables } from './integer-tables';

const output = process.argv[2];

async function hashFile(filePath: string) {
  return new Promise((resolve, reject) => {
    const hash = createHash('sha256')
    const stream = fs.createReadStream(filePath)

    stream.on('data', (chunk) => hash.update(chunk))
    stream.on('end', () => resolve(hash.digest('hex')))
    stream.on('error', reject)
  })
};

function generateTables() {
    
    const tables = makeTables();
    return `
/**
 * Automatically generated file containing the multiplier and shift factors
 * needed for the quadratic stack blur weight factors, for each radius. If you
 * go beyond the allowed radius, you're on your own.
 *
 * This file is generated by the TypeScript file \`./src/js/generate-tables.ts\`,
 * but you probably don't need to worry about it, because we typically commit
 * the generated code.
 */

const int quadratic_weight_maximum_radius = ${ tables.multipliers.length - 1 };
const int quadratic_weight_multipliers[] = { ${ tables.multipliers.join(", ") } };
const unsigned int quadratic_weight_multipliers[] = { ${ tables.shifts.join(", ") } };
`;

}

async function run() {
    if (! output) {
        throw new Error("Missing output file");
    }

    const source = generateTables();

    if (fs.existsSync(output)) {
        const old_hash = await hashFile(output);
        const new_hasher = createHash('sha256');
        new_hasher.update(source);
        const new_hash = new_hasher.digest('hex');
        if (old_hash == new_hash) {
            return;
        }

        fs.rmSync(output);
    }

    fs.writeFileSync(output, source);
}

run();